### ISSUE TITLE
Taretha's Gift is a Horde-only quest.

### ISSUE THREAD

**Issue by rbpaiett** [SwimmingTiger/ClassicCodex#12]
I was roaming around the area trying to get Taretha's Gift quest but it wasn't available to me as an Alliance player.  I looked it up on Wowhead and it said it was Horde-only.  ClassicCodex has it listed for both factions:

<img width="914" alt="Taretha's Gift" src="https://user-images.githubusercontent.com/1621701/72290657-94a69100-3602-11ea-84c0-18d975186b34.png">

Please update this in the addon database.
Thanks for a great addon!

**Comment by YihaoPeng** [comment]
Did you find and click on this quest from the database yourself?

According to the existing code, although the quest is marked as both factions, Alliance players should not automatically see it on the map because the race does not match.

In addition, this quest has pre-quests. Players who have not completed the pre-quests should not automatically see it on the map.

I will fix the display problem in the database, but because I have not an high-level alliance character, I cannot test the quest's automatic display on the map.

**Comment by SwimmingTiger** [comment]
Try fix it at [v1.3.8](https://github.com/SwimmingTiger/ClassicCodex/releases)

**Comment by SwimmingTiger** [comment]
Try fix it at [v1.3.8(]https://github.com/SwimmingTiger/ClassicCodex/releases)

**Comment by rbpaiett** [comment]
Ok, after using the search, now it shows as Horde only, thanks!
